### ISSUE TITLE
No valid ref

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/travis#51] opened 2015-03-11 09:31 UTC
I've been trying to get this setup this morning and all my Travis builds keep failing with `Found no valid ref to match with version` when trying to execute Coveralls.

**Some examples**
Default setup
https://travis-ci.org/davidyell/CakePHP-Seo/jobs/53914563#L100

Trying to specify a specific tag version
https://travis-ci.org/davidyell/CakePHP-Seo/jobs/53916407#L101

**Comment by ceeram** [comment] 2015-03-11 11:15
Closing as this was caused by an incorrect matrix in the .travis.yml config file

**Closed** 2015-03-11 11:14 UTC

**Comment by davidyell** [comment] 2015-03-11 11:16
Thanks, was about to come and close this.

The problem was caused because I had removed the `- CAKE_VERSION=2.6` from my `global` section which meant that when PHCS tried to run it couldn't find a version variable.
